Feature vs4 refactor distance class
R2D2-2018/DISTANCE pull request #12
Opened 2018-06-17 19:14 UTC by JulianvDoorn

## Will do:
In this slice the interface definitions will be explicitly noted. So that external modules will not be required to invoke internal functions in order to filter the requested data.

~~`getSensorData()`~~
~~`medianFilter(int a[], int size)`~~
~~`Distance (hwlib::pin_in HCSR04_pin_in, hwlib::pin_out HCSR04_pin_out, hwlib::pin_in laser_rx_pin)`~~
~~`Distance::getDistance(Enum Sensor, Enum Scale)`~~
~~`HCSR04::getDistance(hwlib::pin_in HCSR04_pin_in, hwlib::pin_out HCSR04_pin_out)`~~
~~`LIDARmini::getDistance()`~~

`getDistance(): Integer`
Applies the median filter to the previous 10 values and the newly read raw value from the sensor specified by setSensor and returns the calculated value in cms. 

`setSensor(Sensor: Auto | Lidar | Ultrasonic)`
Sets the sensor specifier to the sensor specified in the parameter.

`setUnit(Unit: cm | inch)`
Does nothing

`setFilter(Filter: Median | Kalman, Size: Integer)`
Does nothing

#### Note
Some interface functions have been removed from the vertical slice definition. They are not removed from the code, but they are internal components and are not necessary to formulate vertical slices.

Vertical slice: https://trello.com/c/k4wpph8q/49-vs4-discrete-module-interface
Backlog items in this branch:
- https://trello.com/c/gNA68Gfy/59-vs4-refactor-distance-class-2
- https://trello.com/c/DwfI5WjZ/51-vs4-setsensor-1

2018-06-20 13:39 UTC, vasilishomegas requested changes

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
> +    // Get current time
Inline comments like this:
///< Comment
This goes for elsewhere too.

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
>      hwlib::wait_ms(10);
I believe this delay can be 1000 times shorter.
Also, the ```hwlib::wait_ms(2);``` is unnecessary.

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
> +            ;
Use this:
```
while(condition) {
}
```
instead of the semicolon.

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
> +    if (!received) {
This is an unnecessary extra check. Just check if the signal goes high directly.

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
> +        ;
```
while(condition) {
}
```

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
>      // Return distance, when it exceeds it's maximum range; it returns 400.
I don't know if just saying it's 400 if you don't know is the right move.

2018-06-20 13:39 UTC, vasilishomegas commented on src/HCSR04.cpp
> +    // Calculate distance by converting duration to centiseconds,
centiseconds?

2018-06-20 13:39 UTC, vasilishomegas commented on src/distance.hpp
> +    static int convertToInches(int centimeters);
Doxygen mentions two parameters, but function only takes one. It seems like the scale parameter is unnecessary.

2018-06-20 13:39 UTC, vasilishomegas commented on src/hardware_uart.hpp
> +    void putc(char c) override {
No doxygen, but maybe this needs to be addressed in the UART library.

2018-06-20 13:39 UTC, vasilishomegas commented on src/io_stream.hpp
> +    virtual void putc(char c) = 0;
No Doxygen

2018-06-20 13:39 UTC, vasilishomegas commented on src/io_stream.hpp
> +    virtual bool char_available() = 0;
No Doxygen

2018-06-20 13:39 UTC, vasilishomegas commented on src/io_stream.hpp
> +    virtual char getc() = 0;
Doxygen

2018-06-21 08:21 UTC, Dylrak commented on src/io_stream.hpp
> +    virtual void putc(char c) = 0;
Added doxygen for entire IOstream class

2018-06-21 14:28 UTC, vasilishomegas requested changes

2018-06-21 14:28 UTC, vasilishomegas commented on src/lidar_mini.cpp
> +                for (int i = 6; i >= 0; i--) { // Loop for 7 more times to fill in the remaining data package in the array.
Inline comments:
///< Comment

2018-06-21 14:28 UTC, vasilishomegas commented on src/HCSR04.cpp
> +    /// Wait for first signal from echo pin
///< Comment

2018-06-21 14:28 UTC, vasilishomegas commented on src/HCSR04.cpp
> +    int distance = (int)(duration / 58);
Is (int) still necessary? Everything is an int already, although duration is a long long int. If it doesn't work right without it, it's fine.

2018-06-21 14:28 UTC, vasilishomegas commented on test/hcsr04_test_bench.hpp
> +    while (echoPin.get() == true) {
```== true``` is unneccesary

2018-06-21 14:28 UTC, vasilishomegas commented on src/lidar_mini.cpp
> +                hwlib::cout << hwlib::hex << (int)dat[i] << "\r\n";
You don't need the \r, just fix your line endings in PuTTY (I assume that is what you use).

2018-06-22 08:08 UTC, vasilishomegas approved these changes

2018-06-22 08:08 UTC, merged