Development
R2D2-2018/DISTANCE pull request #3
Opened 2018-05-22 10:47 UTC by Leidse

2018-05-24 11:42 UTC, elsavira requested changes
Make sure clang-format is working properly in your IDE. 
Explain variable names where necessary.

2018-05-24 11:42 UTC, elsavira commented on src/filter.cpp
> +	}
Wrong indentation here. Use clang-Format

2018-05-24 11:42 UTC, elsavira commented on src/lidar_mini.hpp
> +    hwlib::target::pin_in RX;
Explain what RX is, or change the name.

2018-05-24 11:42 UTC, elsavira commented on src/lidar_mini.hpp
> +class LIDARmini {
Indents incorrect in this class. Use clang-format as defined on the wiki.

2018-05-24 11:42 UTC, elsavira commented on src/filter.cpp
> + * @brief     Cpp file for the class filter which will contain differnet filters
different*

2018-05-24 11:42 UTC, elsavira commented on src/filter.cpp
> +		for (int j = i; list[j - 1] > list[j]; j-- ) {
Tabs instead of spaces. Use 4 spaces for indentation according to code guidelines.

2018-05-24 11:42 UTC, Qperquin commented on src/uart_protocol.cpp
> +enum uartEnum {
use enum class instead. C++ style.

2018-05-24 11:42 UTC, Qperquin commented on src/uart_protocol.cpp
> +char UARTProtocol::getByte()
Brackets not according to clang-format guidelines. See wiki.

2018-05-24 11:42 UTC, Qperquin commented on src/uart_protocol.hpp
> +        * char : returns a char (which corrosponds to a byte)
corresponds*

2018-05-24 13:30 UTC, elsavira commented
Also update the travis tests with the new template files before re-requesting.

2018-05-25 11:12 UTC, elsavira requested changes
Implement the new travis tests into the module. (Pull the Build-environment, copy all test files from the template-arduino folder, and replace the ones in your current module folder.) 

Sorry about the RX pin, didn't know.

After fixing that, the request is accepted.

2018-05-28 08:16 UTC, Qperquin commented
I can no longer accept this pull request for Sprint 2, since features from Sprint 3 have been pushed to the dev. Please recreate this pull request for the new sprint.

2018-05-28 08:37 UTC, Leidse commented on src/lidar_mini.hpp
> +class LIDARmini {
I have used the clang-format plugin and dont see what is wrong

2018-05-28 08:38 UTC, Leidse commented on src/lidar_mini.hpp
> +    hwlib::target::pin_in RX;
RX is a pin on the arduino and pretty self explanertory

2018-05-28 08:46 UTC, Qperquin commented
Please make a NEW pull request with the correct title for the new slice.

2018-05-28 08:46 UTC, closed without merging